# Generated by Django 3.1.3 on 2020-12-02 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviewapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.IntegerField()),
                ('usability', models.IntegerField()),
                ('content', models.IntegerField()),
                ('overall', models.IntegerField()),
                ('project_rated', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='reviewapp.projects')),
                ('user_rating', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ratings_done', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_rating', 'project_rated')},
            },
        ),
    ]
