# Generated by Django 3.1.3 on 2020-12-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewapp', '0002_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='rating',
            name='overall',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
